apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartodb
spec:
  selector:
    matchLabels:
      name: cartodb
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: cartodb
    spec:
      containers:
      - name: {name}
        image: skydipper/{name}
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: HOSTNAME
            value: '35.233.41.65'
      restartPolicy: Always