apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartodb
spec:
  selector:
    matchLabels:
      name: cartodb
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: cartodb
    spec:
      volumes:
        - name: cartodb-storage
          persistentVolumeClaim:
            claimName: cartodb-storage-pvc
      containers:
      - name: cartodb
        image: skydipper/cartodb
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: HOSTNAME
            value: '35.233.41.65'
        volumeMounts:
          - name: cartodb-storage
            mountPath: /var/lib/postgresql
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cartodb-storage-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
  labels:
    app: cartodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi